export const ALL_ACTIVITIES = [
  { id: 'birding',       label: 'Bird Watching',      emoji: '🦜', desc: 'Dawn trails · Endemic species'             },
  { id: 'farm',          label: 'Farm Life',           emoji: '🌾', desc: 'Harvest season · Organic farming'          },
  { id: 'cooking',       label: 'Traditional Cooking', emoji: '🍛', desc: 'Wood-fire recipes · Local flavours'        },
  { id: 'monsoon',       label: 'Monsoon Trails',      emoji: '🌧️', desc: 'Forest walks · Waterfall hikes'            },
  { id: 'festivals',     label: 'Local Festivals',     emoji: '🎊', desc: 'Seasonal rituals · Cultural events'        },
  { id: 'trekking',      label: 'Trekking & Hiking',   emoji: '🥾', desc: 'Ghats trails · Sunrise walks'              },
  { id: 'fishing',       label: 'River Fishing',       emoji: '🎣', desc: 'Traditional methods · Calm riverbanks'     },
  { id: 'stargazing',    label: 'Star Gazing',         emoji: '🌟', desc: 'Zero light pollution · Night sky'          },
  { id: 'pottery',       label: 'Pottery & Crafts',    emoji: '🏺', desc: 'Local artisans · Hands-on workshops'       },
  { id: 'yoga',          label: 'Yoga & Meditation',   emoji: '🧘', desc: 'Sunrise sessions · Nature backdrop'        },
  { id: 'herbs',         label: 'Herb Garden Walk',    emoji: '🌿', desc: 'Medicinal plants · Forest pharmacy'        },
  { id: 'cricket',       label: 'Village Cricket',     emoji: '🏏', desc: 'Play with locals · Evening matches'        },
  { id: 'night-trails',  label: 'Night Trails',        emoji: '🌙', desc: 'Nocturnal wildlife · Moonlit forest walks' },
  { id: 'culture',       label: 'Cultural Immersion',  emoji: '🎭', desc: 'Local arts · Music · Traditions'           },
  { id: 'cycling',       label: 'Cycling',             emoji: '🚴', desc: 'Village roads · Scenic countryside rides'  },
  { id: 'photography',   label: 'Photography',         emoji: '📷', desc: 'Landscapes · Wildlife · Golden hour'       },
  { id: 'river-walk',    label: 'River Walk',          emoji: '🏞️', desc: 'Riverside trails · Freshwater streams'     },
  { id: 'campfire',      label: 'Campfire Evenings',   emoji: '🔥', desc: 'Stories · Songs · Open sky'                },
]
